Server:
  RunMode: debug
  HttpPort: 8080
  ReadTimeout: 60
  WriteTimeout: 60

Database:
  DBType: mysql
  Username: root
  Password: test
  Host: 127.0.0.1:3306
  DBName: flash_sale_db
  CharSet: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
